version: '3.9'
services:
  splinter-db:
    build: webapp/database
    restart: always
    environment:
      POSTGRES_DB: splinter
      POSTGRES_PASSWORD: 1234
      POSTGRES_USER: postgres

  splinter-frontend:
    build: webapp/frontend/
    restart: always
    environment:
      EMAIL_SERVER_ADDR: 'kask.eti.pg.gda.pl'
      EMAIL_SENDER_HOSTNAME: 'kasklab@eti.pg.gda.pl'
      APP_EXTERNAL_URL: localhost:8888/splinter
      EX_STORE_SPLINTER_PASS: 1234
      EX_STORE_SPLINTER_USER: splinter
      EX_STORE_WEBDAV_PASS: 1234
      EX_STORE_WEBDAV_USER: exam_checker
      POSTGRES_DB: splinter
      POSTGRES_PASSWORD: 1234
      POSTGRES_USER: postgres
    depends_on:
      - "splinter-db"

  splinter-exam-storage:
    build: exam_storage/
    restart: always
    environment:
      EX_STORE_SPLINTER_PASS: 1234
      EX_STORE_SPLINTER_USER: splinter
      EX_STORE_WEBDAV_PASS: 1234
      EX_STORE_WEBDAV_USER: exam_checker
    ports:
      - "8888:80"
    depends_on:
      - "splinter-frontend"
    volumes:
      - ./exam_storage/volumes/www/data/splinter:/www/data/splinter/internal/splinter-data
      - ./exam_storage/volumes/www/data/uploads:/www/data/splinter/external/splinter/uploads

  splinter-inference-engine:
    build: inference_engine/
    restart: always
    environment:
      EX_STORE_SPLINTER_PASS: 1234
      EX_STORE_SPLINTER_USER: splinter
