version: '3.9'
services:
  db:
    container_name: splinter_db
    hostname: splinter_db
    build: database
    restart: always
    env_file:
      - database/db.env
  backend:
    container_name: splinter_backend
    hostname: splinter_backend
    build: webapp/backend/
    depends_on:
      - "db"
    ports:
      - "8080:8080"
  frontend:
    container_name: splinter_frontend
    hostname: splinter_frontend
    build: webapp/frontend/
    ports:
      - "8000:8000"
  exam_storage:
    container_name: splinter_exam_storage
    hostname: splinter_exam_storage
    build: exam_storage/
    restart: always
    ports:
      - "8888:80"
    volumes:
      - type: bind
        source: ./exam_storage/volumes/www/data
        target: /www/data
  inference_engine:
    container_name: splinter_inference_engine
    hostname: splinter_inference_engine
    build: inference_engine/
    ports:
      - "8880:8000"
