version: '3.9'
services:
  splinter-db:
    image: leckijakub/splinter-db
    restart: always
    environment:
      POSTGRES_DB: splinter
      POSTGRES_PASSWORD: 1234
      POSTGRES_USER: postgres

  splinter-frontend:
    image: leckijakub/splinter-frontend
    restart: always
    environment:
      EMAIL_SERVER_ADDR: ''
      EX_STORE_SPLINTER_PASS: 1234
      EX_STORE_SPLINTER_USER: splinter
      EX_STORE_WEBDAV_PASS: 1234
      EX_STORE_WEBDAV_USER: exam_checker
      POSTGRES_DB: splinter
      POSTGRES_PASSWORD: 1234
      POSTGRES_USER: postgres
    depends_on:
      - "splinter-db"

  splinter-exam-storage:
    image: leckijakub/splinter-exam-storage
    restart: always
    environment:
      EX_STORE_SPLINTER_PASS: 1234
      EX_STORE_SPLINTER_USER: splinter
      EX_STORE_WEBDAV_PASS: 1234
      EX_STORE_WEBDAV_USER: exam_checker
    ports:
      - "8888:80"
    volumes:
      - ./exam_storage/volumes/www/data/splinter:/www/data/splinter/internal/splinter-data
      - ./exam_storage/volumes/www/data/uploads:/www/data/splinter/external/splinter/uploads

  splinter-inference-engine:
    image: leckijakub/splinter-inference-engine
    restart: always
    environment:
      EX_STORE_SPLINTER_PASS: 1234
      EX_STORE_SPLINTER_USER: splinter
