version: '3.9'
services:
  splinter-db:
    healthcheck:
      test: [ "CMD", "pg_isready", "-q", "-d", "splinter", "-U", "postgres" ]
      timeout: 45s
      interval: 10s
      retries: 10
    build: webapp/database
    restart: always
    env_file:
      - .env

  splinter-frontend:
    build: webapp/frontend/
    env_file:
      - .env
    ports:
      - "8000:8000"
    depends_on:
      - "splinter-db"

  splinter-exam-storage:
    build:
      context: exam_storage/
      args:
        webdav_user: ${EX_STORE_WEBDAV_USER}
        webdav_pass: ${EX_STORE_WEBDAV_PASS}
        splinter_user: ${EX_STORE_SPLINTER_USER}
        splinter_pass: ${EX_STORE_SPLINTER_PASS}
    env_file:
      - .env
    restart: always
    ports:
      - "8888:80"
    volumes:
      - type: bind
        source: ./exam_storage/volumes/www/data/splinter
        target: /www/data/splinter
      - type: bind
        source: ./exam_storage/volumes/www/data/uploads
        target: /www/data/uploads

  splinter-inference-engine:
    build: inference_engine/
    env_file:
      - .env
    ports:
      - "8880:8000"
