# RANDOM GENERATOR CONFIG SETTING
FONT_SIZE_RANGE = [8, 13]
NUMBER_OF_QUESTIONS_RANGE = [16, 20]
NUMBER_OF_ANSWERS_RANGE = [2, 6]
TOP_MARGIN_RANGE = [0.5, 3] # cm
LEFT_MARGIN_RANGE = [1, 4] # cm
ANSWER_INTERLINE_RANGE = [0, 8] # cm
QUESTION_INTERLINE_RANGE = [6, 14] # cm
