exam_storage:
  url: http://splinter_exam_storage
  port: 80
  exams_dir: "/splinter"
  answer_key_filename: answer_key
  img_extension: pdf
  default_input_dirname: pdfs
  default_output_dirname: students
  exam_storage_user : splinter
  exam_storage_password : 1234

inference:
  answer_threshold: 0.5
  answer_row_shape:
    - 290
    - 60

exam:
  number_of_columns: 5

paths:
  answer_model_path: data/model/saved_model.xml
  index_model_path: data/model/handwritten-english-recognition-0001.xml
