exam_storage:
  url: http://splinter-exam-storage
  port: 81
  exams_dir: "/splinter-data"
  answer_keys_dir: "answers_keys"
  answer_key_filename: answer_key
  img_extension: pdf
  default_input_dirname: pdfs
  default_output_dirname: students
  # exam_storage_user : splinter
  # exam_storage_password : 1234
  metadata_filename: "metadata.json"

inference:
  answer_threshold: 0.5
  answer_row_shape:
    - 290
    - 60
  debug_image: false

exam:
  number_of_columns: 5

paths:
  box_model_path: data/model/saved_model.xml
  ocr_model_path: data/model/handwritten-english-recognition-0001.xml
