exam_storage:
  url: http://localhost
  port: 8888
  answer_key_filename: answer_key
  img_extension: jpg
  default_input_dirname: exams
  default_output_dirname: answers

inference:
  answer_threshold: 0.5

paths:
  answer_model_path: data/model/saved_model.xml
  index_model_path: data/model/handwritten-english-recognition-0001.xml